title: "2026 MLB Fantasy Projections"
author: "Matthew Gillies"
logo: ""

execute:
  execute_notebooks: "off"

latex:
  latex_documents:
    targetname: book.tex

repository:
  url: ""

html:
  use_issues_button: false
  use_repository_button: false
